---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - Radarr:
        href: https://radarr.asbblog.com/
        description: Radarr 
        icon: radarr
        siteMonitor: https://radarr.asbblog.com/
        widget:
            type: radarr
            url: https://radarr.asbblog.com
            key: 89786ab3384c4a748562df01b485b49c
            enableQueue: true
    - QbTorrent: 
        href: https://qb.asbblog.com/
        description: Bit torrent 
        icon: qbittorrent
        siteMonitor: http://qb.asbblog.com/
        widget:
            type: qbittorrent
            url: http://qb.asbblog.com
            username: admin
            password: adminadmin
    - jellyseerr: 
        href: http://jelly.asbblog.com/
        description: jellyseerr 
        icon: jellyseerr
        siteMontior: http://jelly.asbblog.com
        widget:
            type: jellyseerr
            url: http://jelly.asbblog.com
            key: MTcwMzcxMzUwNTY1NWQwZWUyODNlLWVhYmEtNDllOS05ZDFhLTVmMDY5NTVhYjhhMg==
    - Sonarr: 
        href: http://sonarr.asbblog.com/
        description: Sonnar
        siteMonitor: http://sonarr.asbblog.com/
        icon: sonarr
        widget:
            type: sonarr
            url:  http://sonarr.asbblog.com
            key: d9d1f45e906d4564a0563f792ca4b37b
            enableQueue: true # optional, defaults to false
    - prowlarr: 
        href: http://prowlarr.asbblog.com
        description: prowlarr
        icon: prowlarr
        widget:
            type: prowlarr
            url: http://prowlarr.asbblog.com
            key: 4e036a829b1145cf89799e38586e40aa
    - kodi: 
        href: http://kodi.asbblog.com/
        description: kodi
        icon: kodi
    - kodi2: 
        href: http://kodi2.asbblog.com/
        description: kodi2 
        icon: kodi
    - plex:
        href: https://plex.tv
        description: Plex media player 
        icon: plex
        widget:
            type: plex
            url: http://192.168.68.79:32400
            key: Cet9igiJQVNosbeUmj1s
- Media2:
    - Radarr:
        href: https://radarr2.asbblog.com/
        description: Radarr 
        icon: radarr
        siteMonitor: https://radarr2.asbblog.com/
        widget:
            type: radarr
            url: https://radarr2.asbblog.com
            key: 04c84f1ec0e841299f3046ce04356f5f
            enableQueue: true
    - QbTorrent: 
        href: https://qb2.asbblog.com/
        description: Bit torrent 
        icon: qbittorrent
        siteMonitor: http://qb2.asbblog.com/
        widget:
            type: qbittorrent
            url: http://qb2.asbblog.com
            username: admin
            password: adminadmin
    - jellyseerr: 
        href: http://jelly.asbblog.com/
        description: jellyseerr 
        icon: jellyseerr
        siteMontior: http://jelly.asbblog.com
        widget:
            type: jellyseerr
            url: http://jelly.asbblog.com
            key: MTcwMzcxMzUwNTY1NWQwZWUyODNlLWVhYmEtNDllOS05ZDFhLTVmMDY5NTVhYjhhMg==
    - Sonarr: 
        href: http://sonarr2.asbblog.com/
        description: Sonnar
        siteMonitor: http://sonarr2.asbblog.com/
        icon: sonarr
        widget:
            type: sonarr
            url:  http://sonarr2.asbblog.com
            key: 4f3fd7fa3ca5407eb986ddadc149a9c5
            enableQueue: true # optional, defaults to false
    - prowlarr: 
        href: http://prowlarr2.asbblog.com/
        description: prowlarr
        icon: prowlarr
        siteMonitor: http://prowlarr2.asbblog.com/ 
        widget:
            type: prowlarr
            url: http://prowlarr2.asbblog.com
            key: 16bc79a702aa44d1987f7c62efd3d706
- Monitoring:
    - Pi One:
        href: http://pi.asbblog.com/admin
        description: pi hole - main 
        icon: pi-hole
        siteMonitor: https://pi.asbblog.com/admin
        widget:
            type: pihole
            url: https://pi.asbblog.com
            key: d5cee877ac04b8c52c6a182d64781fa30bf3a00d590af20a70bc82f0037bd55e
    - Pi two:
        href: http://pi2.asbblog.com/admin
        description: pi2 hole - main 
        siteMonitor: https://pi2.asbblog.com/admin
        icon: pi-hole
        widget:
            type: pihole
            url: https://pi2.asbblog.com
            key: 3cecde64f6a16ebb7833b98e00f7ebd5bb7a2db73844d6977448eaf697d45e02
    - Portainer:
        href: http://potainer.asbblog.com
        description: portainer container
        siteMonitor: http://portainer.asbblog.com/
        icon: portainer
        widget:
            type: portainer
            url: http://portainer.asbblog.com
            env: 2
            key: ptr_T4o9B+spPrciNRWmFjdv5volVpHDrxehs9OfcOWzwAA=
- Storage Server:
    - NAS:
        href: http://unraid.asbblog.com/login/
        description: Unraid 
        siteMonitor: https://unraid.asbblog.com/login
        icon: unraid
    - NAS: 
        href: http://nas1.asbblog.com/
        description: synology 
        siteMonitor: https://nas1.asbblog.com/signin/
        icon: si-synology
- Automation:
    - Home: 
        href: https://home.asbblog.com
        description: Home Assistance for home
        icon: home-assistant 
        siteMonitor: https://home.asbblog.com
        widget:
            type: homeassistant
            url: https://home.asbblog.com
            key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzZGZkZDUzM2EwMWY0N2ZmYjViYmZmZTZmNGI0NDgwNSIsImlhdCI6MTcwNzkzODA2MywiZXhwIjoyMDIzMjk4MDYzfQ.SzfzMZnVBsexBFO2VIFZQekmN7CnrMd0Ld28sgFe-TI
            custom:
                 - state: light.hue_play_gradient_lightstrip_1
                   label: TV Light strip status 
                 - state: light.signe_gradient_floor_main_room
                   label: Lamp main room 
                 - state: sensor.air_quality_monitor_carbon_dioxide
                   label: carbon monoxide 
                 - state: lock.ix_xdrive50_lock
                   label: Car status
                    
    - Casaos:           
        href: http://casos.asbblog.com
        description : Casaos Asbblog 
        icon: casaos 
    - Casaos Ubuntu: 
        href: http://ubuntu2.asbblog.com/
        descripition: Casaos Ubuntu 
        icon: casaos
- Business:
    - Vikunja:
        href: http://vj.asbblog.com/
        description: Project management tool 
        icon: vikunja
        siteMonitor: http://vj.asbblog.com/
    - Books:
        href: https://books.asbsolutionsgroup.com
        description: Zoho Books for timesheet and invoicing
        icon: mdi-book-account
        siteMonitor: https://books.asbsolutionsgroup.com/
    - Ceipal:
        href: https://talenthire.ceipal.com/signin/
        description: CEIPAL for candidate and job management. 
        icon: mdi-application
    - IT Tools:
        href:  https://tools.asbblog.com/
        description: IT Tools for the developers
        icon: mdi-tools
        siteMonitor: https://tools.asbblog.com/
- Other: 
    - Calander: 
        widget:
            type: calendar
            firstDayInWeek: sunday # optional - defaults to monday
            view: monthly # optional - possible values monthly, agenda
            maxEvents: 10 # optional - defaults to 10
            showTime: true # optional - show time for event happening today - defaults to false
            timezone: America/Los_Angeles # optional and only when timezone is not detected 
            integrations: # optional
                - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr, ical
                  service_group: Media # group name where widget exists
                  service_name: Sonarr # service name for that widget
                  color: teal # optional - defaults to pre-defined color for the service (teal for sonarr)
      