# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: "(^mkdocs\\.yml$)"
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.3'
    hooks:
    -   id: prettier
        types_or:
          - javascript
          - markdown
          - jsx
