blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Questions and Help
    url: https://github.com/gethomepage/homepage/discussions
    about: For support, possible bug reports or general questions.
  - name: ðŸ’¬ Chat
    url: https://discord.gg/k4ruYNrudu
    about: Want to discuss homepage with others? Check out our chat.
  - name: ðŸš€ Feature Request
    url: https://github.com/gethomepage/homepage/discussions/new?category=feature-requests
    about: Remember to search for existing feature requests and "up-vote" any you like
